- name: "Installing Docker-py"
  pip:
    name: docker-py


- name: "Create a login user"
  user:
   name: admin 
   password: '$6$hcJxAWraHfJ$6jtfSPUVchxESYyQRYt8czQeT4XeR0nNd.tDr2nxsqcJE0DxQXArnkTKteDUNFPeI6GGsbOgPgbGcg66LjkkV'
   groups: # Empty by default, here we give it some groups
    - docker
    - sudo
   state: present
   shell: /bin/bash       # Defaults to /bin/bash
   createhome: yes

- name: "Running Juiperhub Docker Image"
  docker_container:
    name: jupyterhub
    image: jupyterhub/jupyterhub
    detach: true
    command: jupyterhub
    ports:
     - "8000:8000"
    state: started

