TWEETER:    
    access_token: "1397965644-WVAG6QSXEBCdHtyAeEgBsKYXEKlkoBBtb58oOAN"
    access_token_secret: "V6V2aUVFmUwkUcHhFzOn4XnwdkbCJPLOL65ZSEnRe9d7O"
    consumer_key: "sZMPWW0zCEVsHnDyO950hWEWN"
    consumer_secret: "KfS6UNO3cTCC6j5xHfjQGaNzBFofDRN98pm5aguCvduIr0UQpg"

QUEUES:
    new_tweets: '../shared_folder/tweets'
    processed_tweets: '../shared_folder/processed_tweets'
    sentiment_tasks: '../shared_folder/sentiment_tasks'
    geo_tasks: '../shared_folder/geo_analyser_tasks'
    

COUCHDB:
    host: 'http://115.146.95.29:5984'
    user: 'admin'
    password: 'group27'