- name: "Installing Git"
  apt: pkg=git state=present

- name: Check if Apache Service Exists
  stat: path=/etc/init.d/apache2
  register: service_status

- name: Stop Apache Service
  service: name=apache2 state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: Check if Nginx Service Exists
  stat: path=/etc/init.d/nginx
  register: nginx_service_status

- name: Stop Nginx Service
  service: name=nginx state=stopped
  when: nginx_service_status.stat.exists
  register: nginx_service_stopped

- name: "Cloning letsencrypt repository"
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: "{{ ansible_user_dir }}/letsencrypt/"
    force: yes

- name: "Creating SSL certificates for {{ v_hostname }}"
  shell: "{{ ansible_user_dir }}/letsencrypt/letsencrypt-auto certonly --standalone -d {{ v_hostname }} -m {{ v_email }} -n --agree-tos"
  become: true

- name: "Copying Certificates in /usr/local/share/ca-certificates/ diretory"
  shell: "cp /etc/letsencrypt/live/{{ v_hostname }}/* /usr/local/share/ca-certificates/"
  become: true

- name: Starting Apache Service
  service: name=apache2 state=started
  when: service_stopped is not skipped

- name: Starting Nginx Service
  service: name=nginx state=started
  when: nginx_service_stopped is not skipped
