-  name: "Git Clone"
   git:
      repo: https://dawerrafi:844715c917aedaae7149743212c0dcdea093b756@github.com/Vitaly-Yakutenko/nectar-project.git
      dest: "~/nectar-project"
      version: "{{ v_branch | default('master') }}"
      force: yes

-  name: "Running requirements.txt"
   pip:
      requirements: "~/nectar-project/requirements.txt"

-  name: "Creating folder for Analysis"
   file:
      path: "~/production"
      state: directory
      mode: 0775

-  name: "Installing Application"
   shell: "cp -R ~/nectar-project/app ~/production/"

-  name: "Copying config.yaml.j2 to server"
   copy:
      src: "../../config.yaml.j2"
      dest: "~/production/"
      mode: 0664

-  name: "Generating config"
   shell: "jinja2 ~/production/config.yaml.j2 -D v_rank={{ v_rank }} -D v_instances={{ v_instances }} ~/nectar-project/ansible/roles/creds.json --format=yaml > ~/production/config.yaml"

-  name: "Make logs folder"
   file:
      path: "~/production/logs"
      state: directory
      mode: 0775

-  name: "Copying Aurin data (1/2)"
   copy:
      src: '~/nectar-project/notebooks/SA2_2016_AUST.csv'
      dest: '/data/SA2_2016_AUST.csv'
      mode: 0664
      remote_src: yes

-  name: "Copying Aurin data (2/2)"
   copy:
      src: '~/nectar-project/notebooks/SA4_data_for_geotagging.json'
      dest: '/data/SA4_data_for_geotagging.json'
      mode: 0664
      remote_src: yes

- block:
  -  name: "Stop Stream Gatherer"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 stream_gatherer.py' | awk '{print $2}')"
     ignore_errors: yes

  -  name: "Stop Sentiment Analyser"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 sentiment_analyser.py' | awk '{print $2}')"
     ignore_errors: yes

  -  name: "Stop Twitter Manager"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 tweets_manager.py' | awk '{print $2}')"
     ignore_errors: yes

  -  name: "Stop Topic Analyser"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 topic_analyser.py' | awk '{print $2}')"
     ignore_errors: yes

  -  name: "Stop Geo Analyser"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 geo_analyser.py' | awk '{print $2}')"
     ignore_errors: yes

  -  name: "Stop API Gatherer"
     shell: "kill -9 $(ps -ef | grep '[p]ython3 api_gatherer.py' | awk '{print $2}')"
     ignore_errors: yes

  become: yes

-  name: "Run Stream Gatherer"
   shell: "nohup python3 stream_gatherer.py > ~/stream_gatherer.log &"
   args:
      chdir: "~/production/app/"

-  name: "Run Sentiment Analyser"
   shell: "nohup python3 sentiment_analyser.py > ~/sentiment_analyser.log &"
   args:
      chdir: "~/production/app/"

-  name: "Run Twitter Manager"
   shell: "nohup python3 tweets_manager.py > ~/tweets_manager.log &"
   args:
      chdir: "~/production/app/"

-  name: "Run Topic Analyser"
   shell: "nohup python3 topic_analyser > ~/topic_analyser.log &"
   args:
      chdir: "~/production/app/"

-  name: "Run Geo Analyser"
   shell: "nohup python3 geo_analyser.py > ~/geo_analyser.log &"
   args:
      chdir: "~/production/app/"

-  name: "Run API Gatherer"
   shell: "nohup python3 api_gatherer.py > ~/api_gatherer.log &"
   args:
      chdir: "~/production/app/"