- name: "Installing Nginx"
  apt:
    pkg: nginx
    state: present

- name: "Installing jinja (1/2)"
  become: yes
  become_flags: '-H'
  pip:
    name: jinja2

- name: "Installing jinja (2/2)"
  become: yes
  become_flags: '-H'
  pip:
    name: jinja2-cli

- name: "Cloning letsencrypt repository"
  git:
    repo: https://github.com/letsencrypt/letsencrypt
    dest: "{{ ansible_user_dir }}/letsencrypt/"
    force: yes

- name: "Stopping Nginx service for SSL certificates creation"
  service:
    name: nginx
    state: stopped

- name: "Creating SSL certificates for {{ v_hostname }}"
  shell: "{{ ansible_user_dir }}/letsencrypt/letsencrypt-auto certonly --standalone -d {{ v_hostname }} -m {{ v_email }} -n --agree-tos"
  become: true

- name: "Copying nginx.conf.j2"
  become: true
  copy:
    src: ../files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf.j2
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: "Configuring Nginx"
  become: yes
  shell: "jinja2 /etc/nginx/nginx.conf.j2 -D domain={{ v_hostname }} -D proxy_port={{ v_nginx.proxy if v_nginx else 'undefined' }} -D https={{ v_nginx.https if v_nginx else False }} > /etc/nginx/nginx.conf"

- name: "Restarting Nginx service"
  become: true
  service:
    name: nginx
    state: restarted