#######################################################################
# GROUP 23
# CITY: Melbourne
# MEMBERS:
#  - Vitaly Yakutenko - 976504
#  - Shireen Hassan - 972461
#  - Himagna Erla - 975172
#  - Areeb Moin - 899193
#  - Syed Muhammad Dawer - 923859
#######################################################################
---
- hosts: all
  become: true
  roles:
  - basic
  - mount

- hosts: jupyter
  become: yes
  vars:
    v_hostname : "{{ inventory_hostname }}"
    v_email: sdawer@student.unimelb.edu.au
    v_client_id: dc7ada54eecdbf6af6fd
    v_client_secret: abf2ce8f6276682401c0a7b1f05446430932909b
    v_root: "/data/shared_folder/public"
    v_nginx:

  roles:
  - ssl
  - nginx
  - jupiterhub

- hosts: couchdb
  become: yes
  vars:
    v_hostname: "{{ inventory_hostname }}"
    v_email: sdawer@student.unimelb.edu.au
    v_nginx:
      proxy: '5984'
    v_http_redirect: yes
    v_https: yes
  roles:
  - ssl
  - nginx

- hosts: production
  vars:
    v_instances: "{{ groups['production'] | length }}"
    v_rank: "{{ groups.production.index(inventory_hostname) }}"
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
  - application